# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29a5ddd6cdf0485cbbe88a0fd5a4c8bf8c515eecb1ebf82eb8bdfaffa147cc90910c20a581b028c941b4ec9a620ebe5741f000e998bcdb7708aaf52d9540b944

test:
  secret_key_base: a670cbe810e7e51c8a4091c1dec58f5ec1e389901137c80f3ef05284bfa22d3159d41fe2e663f8918c4881dfbfe745ecaedfa08f300cd90df0a2a01c68f42222

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
